CREATE TABLE IF NOT EXISTS music (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    shortDescription varchar(100),
    longDescription varchar(1000),
    pathToEntry varchar
);

CREATE TABLE IF NOT EXISTS tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE IF NOT EXISTS music_tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    music_id INTEGER,
    tag_id INTEGER,
    FOREIGN KEY(music_id) REFERENCES music(id),
    FOREIGN KEY(tag_id) REFERENCES tags(id)
);
