name: build check (mikayla dot dev)

env:
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

on:
  push:
    branches:
        # just kidding, these are like, not ready at all
        - never
        - gonna
        - give
        - you
        - up

        # ... COPILOT JUST RICKROLLED ME
        

        # - master
        # # temporarily include dev branches
        # - mongodb
        # - music-streaming
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: install
      run: npm install
    - name: build check
      run: npm run build

  deploy:
    runs-on: self-hosted

    steps:
    - name: deploy service
      run: ""
