name: build check (mikayla dot dev)

on:
  push:
    branches:
        - master
        - next-migration
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: install
      run: npm install
    - name: build check
      run: npm run build
