name: build check (mikayla dot dev)

env:
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

on:
  push:
    branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: install
      run: npm install
    - name: build check
      run: npm run build
